"""One-time generator for sql/schema.sql.

Infers each column's SQL type directly from a sample of the real CSV rather than
hand-authoring ~300 columns across 7 tables, and sidesteps a discrepancy in the provided
column-description file: it names bureau's id column SK_BUREAU_ID, but the real Kaggle
file header is SK_ID_BUREAU. Reading the actual files avoids trusting stale documentation.

Typing rule (deliberately simple — see DECISIONS.md, "Data Loading & Ingest"): id columns -> BIGINT,
TARGET -> SMALLINT, every other numeric column -> DOUBLE PRECISION regardless of whether
pandas sees it as int64 or float64 in the sample, everything else -> TEXT. All identifiers
are lowercase and unquoted so Postgres's default case-folding never becomes a footgun for
LLM-generated SQL later.

Run once: `python -m src.data.build_schema`. Committed sql/schema.sql is the artifact
graders see and what Postgres executes on first boot; this script is how it was produced.
"""
import pandas as pd

from src.data.loader import ID_COLUMNS, TABLE_FILES, table_path
from src.utils.config import settings
from src.utils.logger import get_logger

logger = get_logger(__name__)

SAMPLE_ROWS = 200_000

# Tables where SK_ID_* uniquely identifies one row. The four behaviour/ledger tables
# (bureau_balance, pos_cash_balance, credit_card_balance, installments_payments) have no
# single-column unique key, and installments_payments is known to contain exact duplicate
# rows in the raw data — they are left keyless and just indexed on their join columns.
PRIMARY_KEYS = {
    "application_train": "sk_id_curr",
    "bureau": "sk_id_bureau",
    "previous_application": "sk_id_prev",
}


def infer_column_types(table: str) -> dict[str, str]:
    sample = pd.read_csv(table_path(table), nrows=SAMPLE_ROWS, low_memory=False)
    types: dict[str, str] = {}
    for raw_col in sample.columns:
        name = raw_col.lower()
        if raw_col in ID_COLUMNS:
            types[name] = "BIGINT"
        elif raw_col == "TARGET":
            types[name] = "SMALLINT"
        elif pd.api.types.is_numeric_dtype(sample[raw_col]):
            types[name] = "DOUBLE PRECISION"
        else:
            types[name] = "TEXT"
    return types


def _index_statements(table: str, col_types: dict[str, str]) -> list[str]:
    join_cols = [c for c in ("sk_id_curr", "sk_id_prev", "sk_id_bureau") if c in col_types]
    pk = PRIMARY_KEYS.get(table)
    return [
        f"CREATE INDEX IF NOT EXISTS idx_{table}_{c} ON {table} ({c});"
        for c in join_cols
        if c != pk
    ]


def build_ddl() -> str:
    lines = [
        "-- Auto-generated by `python -m src.data.build_schema` from the real CSV headers",
        "-- and a 200k-row sample of each file. Do not hand-edit; regenerate instead if the",
        "-- source CSVs change shape. See DECISIONS.md for the typing rule.",
        "",
    ]
    for table in TABLE_FILES:
        col_types = infer_column_types(table)
        cols_sql = ",\n".join(f"    {c} {t}" for c, t in col_types.items())
        pk = PRIMARY_KEYS.get(table)
        pk_sql = f",\n    PRIMARY KEY ({pk})" if pk else ""
        lines.append(f"CREATE TABLE IF NOT EXISTS {table} (\n{cols_sql}{pk_sql}\n);")
        lines.append("")
        lines.extend(_index_statements(table, col_types))
        lines.append("")
        logger.info("Inferred %d columns for %s (pk=%s)", len(col_types), table, pk)
    return "\n".join(lines)


if __name__ == "__main__":
    ddl = build_ddl()
    out_path = settings.resolve("sql/schema.sql")
    out_path.write_text(ddl, encoding="utf-8")
    logger.info("Wrote %s", out_path)
